services:
  redis-service:
    image: "redis:bookworm"
    networks:
      - backend-networks
    volumes:
      - "redis-data:/data"
  web-service:
    build: ./web
    ports:
      - "80:5000"
    environment:
      REDIS_URL: "redis://redis-service:6379"
    networks:
      - backend-networks
    depends_on:
      - redis-service
    command: "gunicorn page_tracker.app:app --bind 0.0.0.0:8000"

networks:
  backend-networks:
    
volumes:
  redis-data:
